strans = ["Ukraine", "Russia", "Turckey", "Egypt", "France"]
print (strans)
print(sorted (strans))
print(sorted (strans, reverse=True))
strans.reverse()
print (strans)
strans.reverse()
print (strans)
strans.sort()
print(strans)
strans.sort(reverse=True)
print(strans)
input=raw_input()
